# Generated by Django 3.2.7 on 2021-09-18 12:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0003_auto_20210918_0944'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='gender',
            field=models.TextField(blank=True, choices=[('Male', 'Male'), ('Female', 'Female')]),
        ),
    ]
