# Generated by Django 3.2.7 on 2021-09-17 09:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('awardsApp', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='project',
            old_name='link',
            new_name='project_link',
        ),
        migrations.RenameField(
            model_name='review',
            old_name='comment',
            new_name='review',
        ),
    ]
