# Generated by Django 3.2.7 on 2021-09-17 10:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('awardsApp', '0002_auto_20210917_1259'),
    ]

    operations = [
        migrations.RenameField(
            model_name='rating',
            old_name='post',
            new_name='project',
        ),
    ]
