# Generated by Django 3.2.7 on 2021-09-19 21:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('awardsApp', '0011_alter_project_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='rating',
            name='average_content',
            field=models.IntegerField(blank=True, default=0),
        ),
        migrations.AddField(
            model_name='rating',
            name='average_design',
            field=models.IntegerField(blank=True, default=0),
        ),
        migrations.AddField(
            model_name='rating',
            name='average_usability',
            field=models.IntegerField(blank=True, default=0),
        ),
    ]
