# Generated by Django 3.2.7 on 2021-09-19 21:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('awardsApp', '0012_auto_20210920_0000'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rating',
            name='average_content',
            field=models.FloatField(blank=True, default=0),
        ),
        migrations.AlterField(
            model_name='rating',
            name='average_design',
            field=models.FloatField(blank=True, default=0),
        ),
        migrations.AlterField(
            model_name='rating',
            name='average_usability',
            field=models.FloatField(blank=True, default=0),
        ),
    ]
