# Generated by Django 3.2.7 on 2021-09-20 07:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('awardsApp', '0013_auto_20210920_0018'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='rating',
            name='average_content',
        ),
        migrations.RemoveField(
            model_name='rating',
            name='average_design',
        ),
        migrations.RemoveField(
            model_name='rating',
            name='average_usability',
        ),
    ]
